version: '3.8'

services:
  scanner:
    build: ./backend
    volumes:
      - shared-data:/shared
      - ./sample-data:/data.ro 
    command: python scanner.py /data --output /shared/file_tree_data.json

  backend:
    build:
      context: ./file-tree-timeline/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./file-tree-timeline/backend/data:/data
      - ./file-tree-timeline/backend/shared:/shared