version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - shared-data:/shared
      - ./file_tree_timeline/sample_data/example_project:/data:ro
    command: python unified_backend.py --scan-dir /data/ --output /shared/unified_timeline.json --correlate

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    volumes:
      - shared-data:/usr/share/nginx/html

volumes:
  shared-data:
    driver: local