version: '3.8'

services:
  scanner:
    build: ./backend
    volumes:
      - shared-data:/shared
      - /Users/jakepfitsch/Documents/sample_project_databaseWork/Project_1_Acoustic_Design/:/data.root
    command: python scanner.py /data.root --output /shared/file_tree_data.json

  backend:
    build:
      context: ./file_tree_timeline/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/shared
      - /Users/jakepfitsch/Documents/sample_project_databaseWork/Project_1_Acoustic_Design/:/data.root
    command: python backend.py /data.root --output /shared/file_tree_data.json

volumes:
  shared-data:
    driver: local