apiVersion: v1
kind: ConfigMap
metadata:
  name: filetree-timeline-config
  namespace: filetree-timeline
  labels:
    app: filetree-timeline-visualizer
data:
  # Application configuration
  APP_NAME: "FileTree Timeline Visualizer"
  APP_VERSION: "1.0.0"
  
  # Database configuration
  DB_PATH: "/data/unified_timeline.db"
  DB_BACKUP_PATH: "/data/backups"
  
  # Scanner configuration
  SCANNER_IGNORE_PATTERNS: ".git,__pycache__,node_modules,.DS_Store,.env,.vscode,.idea,*.pyc,.pytest_cache,venv,env,.venv,dist,build,*.db"
  SCANNER_MAX_DEPTH: "10"
  SCANNER_MAX_FILE_SIZE: "104857600"  # 100MB
  
  # Email processing configuration
  EMAIL_SUPPORTED_FORMATS: "eml,msg,txt"
  MILESTONE_CONFIDENCE_THRESHOLD: "0.3"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # CORS configuration for frontend
  CORS_ORIGINS: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Content-Type,Authorization" 