apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: filetree-timeline-visualizer
  namespace: filetree-timeline

resources:
  # Core infrastructure
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - persistent-volumes.yaml
  - rbac.yaml
  
  # Application deployments
  - unified-backend-deployment.yaml
  - scanner-deployment.yaml
  - frontend-deployment.yaml
  
  # Networking
  - services.yaml
  - ingress.yaml
  - network-policy.yaml
  
  # Automation and scaling
  - cronjob.yaml
  - hpa.yaml

commonLabels:
  app: filetree-timeline-visualizer
  version: v1.0.0
  environment: production

commonAnnotations:
  description: "FileTree Timeline Visualizer - Unified timeline visualization system"
  maintainer: "filetree-timeline-team"

images:
  - name: filetree-timeline/unified-backend
    newTag: latest
  - name: filetree-timeline/scanner
    newTag: latest
  - name: filetree-timeline/frontend
    newTag: latest
  - name: filetree-timeline/backup
    newTag: latest

configMapGenerator:
  - name: filetree-timeline-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO

secretGenerator:
  - name: filetree-timeline-secrets
    behavior: merge
    literals:
      - JWT_SECRET=ZmlsZXRyZWUtdGltZWxpbmUtand0LXNlY3JldC1wcm9kdWN0aW9u
      - ENCRYPTION_KEY=ZmlsZXRyZWUtdGltZWxpbmUtZW5jcnlwdGlvbi1rZXktcHJvZHVjdGlvbg== 