apiVersion: v1
kind: PersistentVolume
metadata:
  name: filetree-timeline-data-pv
  labels:
    app: filetree-timeline-visualizer
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/filetree-timeline-data
  storageClassName: filetree-timeline-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filetree-timeline-backup-pv
  labels:
    app: filetree-timeline-visualizer
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/filetree-timeline-backups
  storageClassName: filetree-timeline-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filetree-timeline-storage
  labels:
    app: filetree-timeline-visualizer
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filetree-timeline-data-pvc
  namespace: filetree-timeline
  labels:
    app: filetree-timeline-visualizer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filetree-timeline-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filetree-timeline-backup-pvc
  namespace: filetree-timeline
  labels:
    app: filetree-timeline-visualizer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filetree-timeline-storage
  resources:
    requests:
      storage: 5Gi 